-- Mock Data for AI Priority Testing
-- 50 Customers with diverse scenarios for user_id 1655
-- Includes: Orders (various statuses), Call History (with area_size/crop_type), Appointments

-- Set current date context for relative dates
SET @today = CURDATE();
SET @user_id = 1655;
SET @company_id = 1;

-- ==============================================
-- CLEANUP (Remove old test data to prevent duplicates)
-- ==============================================
DELETE FROM appointments WHERE customer_id IN (SELECT customer_id FROM customers WHERE phone LIKE '08912345%');
DELETE FROM orders WHERE customer_id IN (SELECT customer_id FROM customers WHERE phone LIKE '08912345%');
DELETE FROM call_history WHERE customer_id IN (SELECT customer_id FROM customers WHERE phone LIKE '08912345%');
DELETE FROM customers WHERE phone LIKE '08912345%';

-- ==============================================
-- CUSTOMERS (50 records)
-- Note: customer_ref_id is auto-generated by trigger
-- ==============================================

INSERT INTO customers (first_name, last_name, phone, province, company_id, assigned_to, date_assigned, date_registered, ownership_expires, lifecycle_status, behavioral_status, grade, total_purchases, total_calls) VALUES
-- Tier 1 Scenarios: Appointments Today/Overdue (10 customers)
('สมชาย', 'มีนัดวันนี้', '0891234501', 'นครราชสีมา', @company_id, @user_id, DATE_SUB(@today, INTERVAL 30 DAY), DATE_SUB(@today, INTERVAL 60 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A+', 50000.00, 5),
('วิชัย', 'นัดเกิน', '0891234502', 'ขอนแก่น', @company_id, @user_id, DATE_SUB(@today, INTERVAL 20 DAY), DATE_SUB(@today, INTERVAL 40 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'A', 35000.00, 3),
('มนต์ทพัฒน์', 'นัดสำคัญ', '0891234503', 'อุบลราชธานี', @company_id, @user_id, DATE_SUB(@today, INTERVAL 25 DAY), DATE_SUB(@today, INTERVAL 50 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A', 40000.00, 4),
('ประสิทธิ์', 'ไร่ใหญ่นัด', '0891234504', 'สุรินทร์', @company_id, @user_id, DATE_SUB(@today, INTERVAL 15 DAY), DATE_SUB(@today, INTERVAL 30 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A+', 75000.00, 6),
('อรุณ', 'นัดด่วน', '0891234505', 'บุรีรัมย์', @company_id, @user_id, DATE_SUB(@today, INTERVAL 10 DAY), DATE_SUB(@today, INTERVAL 20 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'B', 25000.00, 2),
('สมหญิง', 'นัดเช้า', '0891234506', 'ร้อยเอ็ด', @company_id, @user_id, DATE_SUB(@today, INTERVAL 35 DAY), DATE_SUB(@today, INTERVAL 70 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A', 45000.00, 7),
('บุญชู', 'นัดบ่าย', '0891234507', 'มหาสารคาม', @company_id, @user_id, DATE_SUB(@today, INTERVAL 5 DAY), DATE_SUB(@today, INTERVAL 10 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'New', 'Hot', 'B', 15000.00, 1),
('เกษม', 'นัดเกิน2วัน', '0891234508', 'ศรีสะเกษ', @company_id, @user_id, DATE_SUB(@today, INTERVAL 40 DAY), DATE_SUB(@today, INTERVAL 80 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'A', 38000.00, 5),
('วิไล', 'นัดหมายเร่งด่วน', '0891234509', 'ยโสธร', @company_id, @user_id, DATE_SUB(@today, INTERVAL 12 DAY), DATE_SUB(@today, INTERVAL 25 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A+', 62000.00, 4),
('ชัยวัฒน์', 'นัดเกิน5วัน', '0891234510', 'อุดรธานี', @company_id, @user_id, DATE_SUB(@today, INTERVAL 18 DAY), DATE_SUB(@today, INTERVAL 35 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'B', 28000.00, 3),

-- Tier 2 Scenarios: Recent Purchase (10 customers)
('สุรพล', 'ซื้อเมื่อวาน', '0891234511', 'หนองคาย', @company_id, @user_id, DATE_SUB(@today, INTERVAL 45 DAY), DATE_SUB(@today, INTERVAL 90 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A', 42000.00, 6),
('พิมพ์ใจ', 'ซื้อ2วัน', '0891234512', 'เลย', @company_id, @user_id, DATE_SUB(@today, INTERVAL 30 DAY), DATE_SUB(@today, INTERVAL 60 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'B', 32000.00, 4),
('ทวี', 'ซื้อ3วัน', '0891234513', 'กาฬสินธุ์', @company_id, @user_id, DATE_SUB(@today, INTERVAL 20 DAY), DATE_SUB(@today, INTERVAL 40 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A+', 58000.00, 5),
('นภา', 'ซื้อ5วัน', '0891234514', 'สกลนคร', @company_id, @user_id, DATE_SUB(@today, INTERVAL 25 DAY), DATE_SUB(@today, INTERVAL 50 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'A', 36000.00, 3),
('ประเวศ', 'ซื้อ7วัน', '0891234515', 'นครพนม', @company_id, @user_id, DATE_SUB(@today, INTERVAL 15 DAY), DATE_SUB(@today, INTERVAL 30 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'B', 27000.00, 2),
('อัมพร', 'ซื้อเพิ่งซื้อ', '0891234516', 'มุกดาหาร', @company_id, @user_id, DATE_SUB(@today, INTERVAL 10 DAY), DATE_SUB(@today, INTERVAL 20 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'New', 'Hot', 'A', 44000.00, 1),
('สมบัติ', 'ซื้อไร่ใหญ่', '0891234517', 'ชัยภูมิ', @company_id, @user_id, DATE_SUB(@today, INTERVAL 35 DAY), DATE_SUB(@today, INTERVAL 70 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A+', 72000.00, 7),
('กนกวรรณ', 'ซื้อวันนี้', '0891234518', 'นครราชสีมา', @company_id, @user_id, DATE_SUB(@today, INTERVAL 5 DAY), DATE_SUB(@today, INTERVAL 10 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A', 39000.00, 4),
('วิรัตน์', 'ซื้อ4วัน', '0891234519', 'ขอนแก่น', @company_id, @user_id, DATE_SUB(@today, INTERVAL 40 DAY), DATE_SUB(@today, INTERVAL 80 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'B', 29000.00, 5),
('สุดารัตน์', 'ซื้อ6วัน', '0891234520', 'อุบลราชธานี', @company_id, @user_id, DATE_SUB(@today, INTERVAL 22 DAY), DATE_SUB(@today, INTERVAL 45 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A', 41000.00, 3),

-- Tier 3 Scenarios: Restock Cycle (15 customers)
('ธนากร', 'รอบ30วัน', '0891234521', 'สุรินทร์', @company_id, @user_id, DATE_SUB(@today, INTERVAL 90 DAY), DATE_SUB(@today, INTERVAL 120 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'A', 35000.00, 8),
('วาสนา', 'รอบ60วัน', '0891234522', 'บุรีรัมย์', @company_id, @user_id, DATE_SUB(@today, INTERVAL 120 DAY), DATE_SUB(@today, INTERVAL 180 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'B', 28000.00, 6),
('ชาญชัย', 'รอบ90วัน', '0891234523', 'ร้อยเอ็ด', @company_id, @user_id, DATE_SUB(@today, INTERVAL 180 DAY), DATE_SUB(@today, INTERVAL 270 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'A', 42000.00, 9),
('จินตนา', 'ใกล้รอบ30', '0891234524', 'มหาสารคาม', @company_id, @user_id, DATE_SUB(@today, INTERVAL 60 DAY), DATE_SUB(@today, INTERVAL 90 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A+', 51000.00, 5),
('ปรีชา', 'ใกล้รอบ60', '0891234525', 'ศรีสะเกษ', @company_id, @user_id, DATE_SUB(@today, INTERVAL 100 DAY), DATE_SUB(@today, INTERVAL 160 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A', 38000.00, 7),
('นันทนา', 'ใกล้รอบ90', '0891234526', 'ยโสธร', @company_id, @user_id, DATE_SUB(@today, INTERVAL 150 DAY), DATE_SUB(@today, INTERVAL 240 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'B', 31000.00, 6),
('สุทัศน์', 'รอบ120วัน', '0891234527', 'อุดรธานี', @company_id, @user_id, DATE_SUB(@today, INTERVAL 240 DAY), DATE_SUB(@today, INTERVAL 360 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'A', 46000.00, 10),
('ภาวิณี', 'ใกล้รอบ120', '0891234528', 'หนองคาย', @company_id, @user_id, DATE_SUB(@today, INTERVAL 200 DAY), DATE_SUB(@today, INTERVAL 320 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A+', 64000.00, 8),
('รัชพล', 'ข้าว90วัน', '0891234529', 'เลย', @company_id, @user_id, DATE_SUB(@today, INTERVAL 140 DAY), DATE_SUB(@today, INTERVAL 230 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A', 43000.00, 6),
('สายใจ', 'มันสำปะหลัง', '0891234530', 'กาฬสินธุ์', @company_id, @user_id, DATE_SUB(@today, INTERVAL 110 DAY), DATE_SUB(@today, INTERVAL 170 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'B', 33000.00, 5),
('ธีรพงษ์', 'ผัก30วัน', '0891234531', 'สกลนคร', @company_id, @user_id, DATE_SUB(@today, INTERVAL 70 DAY), DATE_SUB(@today, INTERVAL 100 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A', 37000.00, 4),
('วรรณา', 'อ้อย120วัน', '0891234532', 'นครพนม', @company_id, @user_id, DATE_SUB(@today, INTERVAL 190 DAY), DATE_SUB(@today, INTERVAL 310 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'A+', 68000.00, 9),
('เกรียงไกร', 'รอบสั่งเร็ว', '0891234533', 'มุกดาหาร', @company_id, @user_id, DATE_SUB(@today, INTERVAL 50 DAY), DATE_SUB(@today, INTERVAL 80 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'B', 26000.00, 3),
('ปาริชาติ', 'รอบสั่งกลาง', '0891234534', 'ชัยภูมิ', @company_id, @user_id, DATE_SUB(@today, INTERVAL 130 DAY), DATE_SUB(@today, INTERVAL 190 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'A', 40000.00, 7),
('กิตติพงษ์', 'รอบสั่งช้า', '0891234535', 'นครราชสีมา', @company_id, @user_id, DATE_SUB(@today, INTERVAL 210 DAY), DATE_SUB(@today, INTERVAL 330 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'A', 45000.00, 8),

-- Tier 4 Scenarios: Call Engagement (10 customers)
('สมปอง', 'สนใจมาก', '0891234536', 'ขอนแก่น', @company_id, @user_id, DATE_SUB(@today, INTERVAL 28 DAY), DATE_SUB(@today, INTERVAL 55 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A', 39000.00, 4),
('รุ่งทิวา', 'ไม่รับสาย', '0891234537', 'อุบลราชธานี', @company_id, @user_id, DATE_SUB(@today, INTERVAL 32 DAY), DATE_SUB(@today, INTERVAL 65 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'B', 27000.00, 5),
('ธงชัย', 'ขอโทรกลับ', '0891234538', 'สุรินทร์', @company_id, @user_id, DATE_SUB(@today, INTERVAL 24 DAY), DATE_SUB(@today, INTERVAL 48 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A', 41000.00, 3),
('พรทิพย์', 'สนใจปุ๋ย', '0891234539', 'บุรีรัมย์', @company_id, @user_id, DATE_SUB(@today, INTERVAL 36 DAY), DATE_SUB(@today, INTERVAL 72 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A+', 55000.00, 6),
('วีระ', 'ไลน์ไม่ตอบ', '0891234540', 'ร้อยเอ็ด', @company_id, @user_id, DATE_SUB(@today, INTERVAL 29 DAY), DATE_SUB(@today, INTERVAL 58 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'B', 30000.00, 4),
('สุภาพ', 'โทรติดตาม', '0891234541', 'มหาสารคาม', @company_id, @user_id, DATE_SUB(@today, INTERVAL 33 DAY), DATE_SUB(@today, INTERVAL 66 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A', 37000.00, 5),
('นิภา', 'สนใจสารเคมี', '0891234542', 'ศรีสะเกษ', @company_id, @user_id, DATE_SUB(@today, INTERVAL 27 DAY), DATE_SUB(@today, INTERVAL 54 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A', 42000.00, 3),
('สมศักดิ์', 'ขอนัดพบ', '0891234543', 'ยโสธร', @company_id, @user_id, DATE_SUB(@today, INTERVAL 31 DAY), DATE_SUB(@today, INTERVAL 62 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A+', 59000.00, 4),
('จิราพร', 'โทรไม่ติด', '0891234544', 'อุดรธานี', @company_id, @user_id, DATE_SUB(@today, INTERVAL 26 DAY), DATE_SUB(@today, INTERVAL 52 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'B', 28000.00, 6),
('พิเชษฐ์', 'สนใจมากๆ', '0891234545', 'หนองคาย', @company_id, @user_id, DATE_SUB(@today, INTERVAL 34 DAY), DATE_SUB(@today, INTERVAL 68 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Hot', 'A', 44000.00, 5),

-- Fatigue Protection Scenarios (5 customers)
('อนุชา', 'โทรวันนี้', '0891234546', 'เลย', @company_id, @user_id, DATE_SUB(@today, INTERVAL 15 DAY), DATE_SUB(@today, INTERVAL 30 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'B', 25000.00, 7),
('สุนีย์', 'โทรเมื่อวาน', '0891234547', 'กาฬสินธุ์', @company_id, @user_id, DATE_SUB(@today, INTERVAL 19 DAY), DATE_SUB(@today, INTERVAL 38 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Warm', 'C', 18000.00, 5),
('บุญส่ง', 'โทร2วันก่อน', '0891234548', 'สกลนคร', @company_id, @user_id, DATE_SUB(@today, INTERVAL 23 DAY), DATE_SUB(@today, INTERVAL 46 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Cold', 'C', 16000.00, 4),
('มาลี', 'ลูกค้าใหม่', '0891234549', 'นครพนม', @company_id, @user_id, DATE_SUB(@today, INTERVAL 3 DAY), DATE_SUB(@today, INTERVAL 3 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'New', 'Hot', 'B', 5000.00, 1),
('ประดิษฐ์', 'เกรดต่ำ', '0891234550', 'มุกดาหาร', @company_id, @user_id, DATE_SUB(@today, INTERVAL 45 DAY), DATE_SUB(@today, INTERVAL 90 DAY), DATE_ADD(@today, INTERVAL 30 DAY), 'Old', 'Cold', 'D', 8000.00, 3);

-- ==============================================
-- ORDERS (Varied statuses and cycles)
-- ==============================================

-- Customer 001: Recent + Cycle 30 days
INSERT INTO orders (id, customer_id, order_date, order_status, total_amount, payment_status, creator_id) VALUES
('ORD-001-1', (SELECT customer_id FROM customers WHERE phone = '0891234501'), DATE_SUB(@today, INTERVAL 1 DAY), 'Delivered', 8500.00, 'Paid', @user_id),
('ORD-001-2', (SELECT customer_id FROM customers WHERE phone = '0891234501'), DATE_SUB(@today, INTERVAL 31 DAY), 'Delivered', 9200.00, 'Paid', @user_id),
('ORD-001-3', (SELECT customer_id FROM customers WHERE phone = '0891234501'), DATE_SUB(@today, INTERVAL 62 DAY), 'Delivered', 8800.00, 'Paid', @user_id);

-- Customer 011: Just purchased (1 day ago)
INSERT INTO orders (id, customer_id, order_date, order_status, total_amount, payment_status, creator_id) VALUES  
('ORD-011-1', (SELECT customer_id FROM customers WHERE phone = '0891234511'), DATE_SUB(@today, INTERVAL 1 DAY), 'Delivered', 12000.00, 'Paid', @user_id);

-- Customer 012: Purchased 2 days ago
INSERT INTO orders (id, customer_id, order_date, order_status, total_amount, payment_status, creator_id) VALUES
('ORD-012-1', (SELECT customer_id FROM customers WHERE phone = '0891234512'), DATE_SUB(@today, INTERVAL 2 DAY), 'Approved', 9500.00, 'Paid', @user_id);

-- Customer 013: Purchased 3 days ago
INSERT INTO orders (id, customer_id, order_date, order_status, total_amount, payment_status, creator_id) VALUES
('ORD-013-1', (SELECT customer_id FROM customers WHERE phone = '0891234513'), DATE_SUB(@today, INTERVAL 3 DAY), 'Confirmed', 15000.00, 'Paid', @user_id);

-- Customer 021-035: Various cycles with 3-5 orders each
INSERT INTO orders (id, customer_id, order_date, order_status, total_amount, payment_status, creator_id) VALUES
-- Customer 021: 30-day cycle (3 orders)
('ORD-021-1', (SELECT customer_id FROM customers WHERE phone = '0891234521'), DATE_SUB(@today, INTERVAL 28 DAY), 'Pending', 7500.00, 'Unpaid', @user_id),
('ORD-021-2', (SELECT customer_id FROM customers WHERE phone = '0891234521'), DATE_SUB(@today, INTERVAL 58 DAY), 'Delivered', 7200.00, 'Paid', @user_id),
('ORD-021-3', (SELECT customer_id FROM customers WHERE phone = '0891234521'), DATE_SUB(@today, INTERVAL 88 DAY), 'Delivered', 6800.00, 'Paid', @user_id),

-- Customer 024: Near cycle (95% of 30 days)
('ORD-024-1', (SELECT customer_id FROM customers WHERE phone = '0891234524'), DATE_SUB(@today, INTERVAL 29 DAY), 'Pending', 11000.00, 'Unpaid', @user_id),
('ORD-024-2', (SELECT customer_id FROM customers WHERE phone = '0891234524'), DATE_SUB(@today, INTERVAL 59 DAY), 'Delivered', 10500.00, 'Paid', @user_id),
('ORD-024-3', (SELECT customer_id FROM customers WHERE phone = '0891234524'), DATE_SUB(@today, INTERVAL 89 DAY), 'Delivered', 10200.00, 'Paid', @user_id),

-- Customer 023: 90-day cycle
('ORD-023-1', (SELECT customer_id FROM customers WHERE phone = '0891234523'), DATE_SUB(@today, INTERVAL 85 DAY), 'Cancelled', 8000.00, 'Unpaid', @user_id),
('ORD-023-2', (SELECT customer_id FROM customers WHERE phone = '0891234523'), DATE_SUB(@today, INTERVAL 175 DAY), 'Delivered', 9300.00, 'Paid', @user_id),
('ORD-023-3', (SELECT customer_id FROM customers WHERE phone = '0891234523'), DATE_SUB(@today, INTERVAL 265 DAY), 'Delivered', 8900.00, 'Paid', @user_id),

-- Customer 027: 120-day cycle
('ORD-027-1', (SELECT customer_id FROM customers WHERE phone = '0891234527'), DATE_SUB(@today, INTERVAL 110 DAY), 'Pending', 13000.00, 'Partial', @user_id),
('ORD-027-2', (SELECT customer_id FROM customers WHERE phone = '0891234527'), DATE_SUB(@today, INTERVAL 230 DAY), 'Delivered', 12500.00, 'Paid', @user_id),
('ORD-027-3', (SELECT customer_id FROM customers WHERE phone = '0891234527'), DATE_SUB(@today, INTERVAL 350 DAY), 'Delivered', 11800.00, 'Paid', @user_id),

-- Customer 028: Near 120-day cycle (95%)
('ORD-028-1', (SELECT customer_id FROM customers WHERE phone = '0891234528'), DATE_SUB(@today, INTERVAL 115 DAY), 'Pending', 19000.00, 'Unpaid', @user_id),
('ORD-028-2', (SELECT customer_id FROM customers WHERE phone = '0891234528'), DATE_SUB(@today, INTERVAL 235 DAY), 'Delivered', 18500.00, 'Paid', @user_id),
('ORD-028-3', (SELECT customer_id FROM customers WHERE phone = '0891234528'), DATE_SUB(@today, INTERVAL 355 DAY), 'Delivered', 17200.00, 'Paid', @user_id);

-- ==============================================
-- CALL HISTORY (With area_size and crop_type)
-- ==============================================

INSERT INTO call_history (customer_id, date, caller, status, result, notes, area_size, crop_type) VALUES
-- Tier 4: Engagement signals
((SELECT customer_id FROM customers WHERE phone = '0891234536'), DATE_SUB(@today, INTERVAL 2 DAY), 'ทีมขาย', 'Completed', 'สนใจ', 'ลูกค้าสนใจปุ๋ยสูตรใหม่ อยากลองใช้ ขอเสนอราคา', 85.5, 'ข้าว'),
((SELECT customer_id FROM customers WHERE phone = '0891234537'), DATE_SUB(@today, INTERVAL 1 DAY), 'ทีมขาย', 'Attempted', 'ไม่ติด', 'โทรไม่รับ จะลองโทรใหม่พรุ่งนี้', 45.0, 'มันสำปะหลัง'),
((SELECT customer_id FROM customers WHERE phone = '0891234538'), DATE_SUB(@today, INTERVAL 3 DAY), 'ทีมขาย', 'Pending', 'โทรกลับ', 'ลูกค้าขอให้โทรกลับช่วงบ่าย 14:00', 120.0, 'อ้อย'),
((SELECT customer_id FROM customers WHERE phone = '0891234539'), DATE_SUB(@today, INTERVAL 1 DAY), 'ทีมขาย', 'Completed', 'สนใจมาก', 'สนใจปุ๋ยเคมีและสารกำจัดวัชพืช ขอใบเสนอราคา', 150.0, 'ข้าว'),
((SELECT customer_id FROM customers WHERE phone = '0891234540'), DATE_SUB(@today, INTERVAL 2 DAY), 'ทีมขาย', 'Attempted', 'ไม่รับสาย', 'โทร 3 รอบไม่รับ', 32.0, 'ผัก'),
((SELECT customer_id FROM customers WHERE phone = '0891234541'), DATE_SUB(@today, INTERVAL 4 DAY), 'ทีมขาย', 'Completed', 'สนใจ', 'ถามรายละเอียดสินค้า', 68.0, 'ข้าวโพด'),
((SELECT customer_id FROM customers WHERE phone = '0891234542'), DATE_SUB(@today, INTERVAL 2 DAY), 'ทีมขาย', 'Completed', 'สนใจสารเคมี', 'ต้องการสารฆ่าแมลงด่วน', 95.0, 'ข้าว'),
((SELECT customer_id FROM customers WHERE phone = '0891234543'), DATE_SUB(@today, INTERVAL 3 DAY), 'ทีมขาย', 'Pending', 'ขอโทรกลับวันจันทร์', 'ขอนัดพบที่ไร่', 180.5, 'อ้อย'),
((SELECT customer_id FROM customers WHERE phone = '0891234544'), DATE_SUB(@today, INTERVAL 1 DAY), 'ทีมขาย', 'Attempted', 'ไม่ติดสาย', 'โทรไม่ตอบ', 52.0, 'มันสำปะหลัง'),
((SELECT customer_id FROM customers WHERE phone = '0891234545'), DATE_SUB(@today, INTERVAL 2 DAY), 'ทีมขาย', 'Completed', 'สนใจมากๆ', 'อยากสั่งเร็วๆ รอใบเสนอราคา', 110.0, 'ข้าว'),

-- Fatigue scenarios
((SELECT customer_id FROM customers WHERE phone = '0891234546'), @today, 'ทีมขาย', 'Completed', 'ติดตามสินค้า', 'โทรติดตามออเดอร์ล่าสุด', 28.0, 'ผัก'),
((SELECT customer_id FROM customers WHERE phone = '0891234547'), DATE_SUB(@today, INTERVAL 1 DAY), 'ทีมขาย', 'Completed', 'ติดตาม', 'โทรเช็คความพร้อม', 35.0, 'ข้าว'),
((SELECT customer_id FROM customers WHERE phone = '0891234548'), DATE_SUB(@today, INTERVAL 2 DAY), 'ทีมขาย', 'Completed', 'สอบถาม', 'สอบถามความต้องการ', 42.0, 'มันสำปะหลัง'),

-- Farm size variety
((SELECT customer_id FROM customers WHERE phone = '0891234504'), DATE_SUB(@today, INTERVAL 5 DAY), 'ทีมขาย', 'Completed', 'เจรจา', 'ไร่ใหญ่ 200 ไร่ เจรจาราคาปุ๋ย', 200.0, 'ข้าว'),
((SELECT customer_id FROM customers WHERE phone = '0891234517'), DATE_SUB(@today, INTERVAL 3 DAY), 'ทีมขาย', 'Completed', 'ติดตาม', 'ไร่ใหญ่ 150 ไร่ สนใจสินค้าใหม่', 150.0, 'อ้อย'),
((SELECT customer_id FROM customers WHERE phone = '0891234528'), DATE_SUB(@today, INTERVAL 6 DAY), 'ทีมขาย', 'Completed', 'เช็คสต็อก', 'ไร่ใหญ่ 180 ไร่ ถามเรื่องสต๊อก', 180.0, 'ข้าว');

-- ==============================================
-- APPOINTMENTS
-- ==============================================

INSERT INTO appointments (customer_id, date, title, status, notes) VALUES
-- Today's appointments (Tier 1 - highest priority)
((SELECT customer_id FROM customers WHERE phone = '0891234501'), CONCAT(@today, ' 09:00:00'), 'นัดดูสินค้า', 'รอดำเนินการ', 'นัดพบที่ไร่เพื่อดูสภาพพืช'),
((SELECT customer_id FROM customers WHERE phone = '0891234503'), CONCAT(@today, ' 14:00:00'), 'นัดเจรจาราคา', 'รอดำเนินการ', 'ต้องการสั่งปุ๋ยจำนวนมาก'),
((SELECT customer_id FROM customers WHERE phone = '0891234506'), CONCAT(@today, ' 10:30:00'), 'นัดส่งสินค้า', 'รอดำเนินการ', 'ส่งปุ๋ยที่สั่งไว้'),
((SELECT customer_id FROM customers WHERE phone = '0891234507'), CONCAT(@today, ' 16:00:00'), 'นัดให้คำปรึกษา', 'รอดำเนินการ', 'ปรึกษาเรื่องการใช้สารเคมี'),

-- Overdue appointments (Tier 1)
((SELECT customer_id FROM customers WHERE phone = '0891234502'), DATE_SUB(@today, INTERVAL 2 DAY), 'นัดติดตามผล', 'รอดำเนินการ', 'นัดเกิน 2 วัน ต้องติดตามด่วน'),
((SELECT customer_id FROM customers WHERE phone = '0891234508'), DATE_SUB(@today, INTERVAL 3 DAY), 'นัดพบที่ไร่', 'รอดำเนินการ', 'นัดเกิน 3 วัน'),
((SELECT customer_id FROM customers WHERE phone = '0891234510'), DATE_SUB(@today, INTERVAL 5 DAY), 'นัดส่งเอกสาร', 'รอดำเนินการ', 'นัดเกิน 5 วัน ควรติดตาม'),

-- Completed appointments
((SELECT customer_id FROM customers WHERE phone = '0891234511'), DATE_SUB(@today, INTERVAL 1 DAY), 'นัดส่งสินค้า', 'เสร็จสิ้น', 'ส่งสินค้าเรียบร้อยแล้ว'),
((SELECT customer_id FROM customers WHERE phone = '0891234512'), DATE_SUB(@today, INTERVAL 2 DAY), 'นัดเก็บเงิน', 'เสร็จสิ้น', 'เก็บเงินครบแล้ว'),

-- Future appointments (should not affect score much)
((SELECT customer_id FROM customers WHERE phone = '0891234520'), DATE_ADD(@today, INTERVAL 3 DAY), 'นัดดูสินค้าใหม่', 'รอดำเนินการ', 'นัดในอนาคต'),
((SELECT customer_id FROM customers WHERE phone = '0891234525'), DATE_ADD(@today, INTERVAL 7 DAY), 'นัดส่งปุ๋ย', 'รอดำเนินการ', 'นัดในอนาคต');

COMMIT;
